<!DOCTYPE html>
<html>
<head>
    <title>Tickets Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #2c3e50;
        }
        .info {
            margin-bottom: 20px;
        }
        .info p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #3498db;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .priority-critical {
            color: #e74c3c;
            font-weight: bold;
        }
        .priority-high {
            color: #e67e22;
            font-weight: bold;
        }
        .priority-medium {
            color: #f39c12;
        }
        .priority-low {
            color: #27ae60;
        }
        .status-open {
            color: #3498db;
        }
        .status-in-progress {
            color: #f39c12;
        }
        .status-resolved {
            color: #27ae60;
        }
        .status-closed {
            color: #95a5a6;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #7f8c8d;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Support Tickets Report</h1>
        <p>{{ config('app.name') }}</p>
    </div>

    <div class="info">
        <p><strong>Report Period:</strong> {{ \Carbon\Carbon::parse($start_date)->format('F d, Y') }} - {{ \Carbon\Carbon::parse($end_date)->format('F d, Y') }}</p>
        <p><strong>Generated On:</strong> {{ $generated_at->format('F d, Y h:i A') }}</p>
        <p><strong>Total Tickets:</strong> {{ $tickets->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Ticket #</th>
                <th>Subject</th>
                <th>Client</th>
                <th>Category</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Agent</th>
                <th>Created</th>
                <th>Resolved</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tickets as $ticket)
            <tr>
                <td>{{ $ticket->ticket_number }}</td>
                <td>{{ Str::limit($ticket->subject, 30) }}</td>
                <td>{{ $ticket->client->user->name }}</td>
                <td>{{ $ticket->category->name }}</td>
                <td class="priority-{{ strtolower($ticket->priority) }}">{{ $ticket->priority }}</td>
                <td class="status-{{ strtolower(str_replace(' ', '-', $ticket->status)) }}">{{ $ticket->status }}</td>
                <td>{{ $ticket->agent ? $ticket->agent->user->name : 'Unassigned' }}</td>
                <td>{{ $ticket->created_at->format('m/d/Y') }}</td>
                <td>{{ $ticket->resolved_at ? $ticket->resolved_at->format('m/d/Y') : '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was automatically generated by {{ config('app.name') }} Support System</p>
    </div>
</body>
</html>